# Generated by Django 4.2.7 on 2023-11-06 02:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id_notas', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titile', models.CharField(max_length=150)),
                ('body_text', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
